version: '3.8'

services:
  hibernate_postgres:
    image: postgres
    container_name: hibernate_postgres
    read_only: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=hibernateDb
    expose:
      - "54322"
    ports:
      - "54322:54322"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    command: -p 54322
  redis-hibernate:
      container_name: redis-hibernate
      image: redis
      ports:
        - "6377:6379"
      expose:
        - "6377"
      command: redis-server --port 6379
volumes:
  postgres-volume: